name: automerge
on:
  pull_request:
    types:
      - labeled
      - opened
      - ready_for_review
  check_suite:
    types:
      - completed
  status: {success}
env:
  GITHUB_TOKEN: "${{ secrets.AUTOMATION_ACCESS_TOKEN }}"
  MERGE_LABELS: "automerge"
  UPDATE_LABELS: "auto-pr,merge-failed"
  MERGE_REQUIRED_APPROVALS: "0"
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"