name: Merge any release branch to uat
permissions:
  # [Learn more about automatic token authentication permissions]
  # (https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)
  # Permissions required for merging branches
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to merge branches
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - staging
      - 'release/*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge staging or release/* -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Pull Request
        if: ${{ failure() }} 
        uses: repo-sync/pull-request@master
        with:
          destination_branch: "main"
          pr_title: "[Conflict] Try to merge ${{ github.ref_name }} into develop" # Title of pull request
          # pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_body: 'Pr created by automation because of a conflict'
          # pr_reviewer: "MADdantas"                         # Comma-separated list (no spaces)
          pr_assignee: ${{github.actor}}                         # Comma-separated list (no spaces)
          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          # pr_milestone: "Milestone 1"                       # Milestone name
          pr_draft: true                                    # Creates pull request as draft
          # pr_allow_empty: true                              # Creates pull request even if there are no changes
