name: Merge any release or staging branch to develop
permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - staging
      - 'release/*'
env:
  NEW_BRANCH: ${{ 'merge/' }}${{ github.ref_name }}
  GITHUB_TOKEN: ${{ secrets.AUTOMATION_ACCESS_TOKEN }}
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Creating new branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: 'refs/heads/${{ env.NEW_BRANCH }}'

      - uses: actions/checkout@master

      - name: Create Pull Request
        uses: repo-sync/pull-request@master
        with:
          destination_branch: 'main'
          source_branch: '${{ env.NEW_BRANCH }}'
          pr_title: "[Automation] ${{ env.NEW_BRANCH }} into develop" # Title of pull request
          pr_body: 'Pr created by automation because of a conflict'
          pr_assignee: ${{github.actor}}                         # Comma-separated list (no spaces)
          pr_label: "merge-failed,automerge"             # Comma-separated list (no spaces)
          pr_draft: false                                    # Creates pull request as draft