name: Merge any release branch to uat
permissions:
  # [Learn more about automatic token authentication permissions]
  # (https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)
  # Permissions required for merging branches
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to merge branches
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - staging
      - 'release/*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: 'merge/${{ github.ref_name }}'
    steps:
      - name: Creating new branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATION_ACCESS_TOKEN }}
        with:
          branch: 'refs/heads/${{ NEW_BRANCH }}'
      - name: Create Pull Request
        uses: repo-sync/pull-request@master
        with:
          destination_branch: '${{ NEW_BRANCH }}'
          pr_title: "Merge ${{ NEW_BRANCH }} into develop" # Title of pull request
          pr_body: 'Pr created by automation because of a conflict'
          pr_assignee: ${{github.actor}}                         # Comma-separated list (no spaces)
          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          pr_draft: true                                    # Creates pull request as draft
