name: Merge any release branch to uat
permissions:
  # [Learn more about automatic token authentication permissions]
  # (https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)
  # Permissions required for merging branches
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to merge branches
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - staging
      - 'release/*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      name: Creating new branch
        - uses: peterjgrainger/action-create-branch@v2.2.0
          env:
            GITHUB_TOKEN: ${{ secrets.AUTOMATION_ACCESS_TOKEN }}
          with:
            branch: 'refs/heads/merge/${{ github.ref_name }}'

      - uses: actions/checkout@master

      - name: Merge staging or release/* -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: fopina/upstream-to-pr@v1
        with:    
          token: ${{ secrets.AUTOMATION_ACCESS_TOKEN }}
          upstream-repository: https://github.com/MADdantas/portifolio
          upstream-branch: main
