name: Create PR from dev to merge/*
permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - 'release/*'
env:
  NEW_BRANCH: ${{ 'merge/' }}${{ github.ref_name }}
  GITHUB_TOKEN: ${{ secrets.AUTOMATION_ACCESS_TOKEN }}
jobs:
  create-pr-to-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          echo "Creating new branch"
          git checkout -b ${{ env.NEW_BRANCH }}
          git checkout ${{ env.NEW_BRANCH }}
          echo "Mergin ${{ github.ref_name }} into ${{ env.NEW_BRANCH }}"
          git merge ${{ github.ref_name }}
          git commit -m "Automation get latest commits"
          git push -u origin ${{ env.NEW_BRANCH }}
          
      - name: Create Pull Request
        uses: repo-sync/pull-request@master
        with:
          destination_branch: 'main'
          source_branch: '${{ env.NEW_BRANCH }}'
          pr_title: "[Automation] ${{ github.ref_name }} into develop" # Title of pull request
          pr_body: 'Pr created by automation to run tests'
          pr_assignee: ${{github.actor}}
