name: Merge any release branch to uat
permissions:
  # [Learn more about automatic token authentication permissions]
  # (https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)
  # Permissions required for merging branches
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to merge branches
  contents: write
on:
  push:
    branches:
      - staging
      - 'release/*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge staging or release/* -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
      - uses: actions/checkout@v3

      - name: Create Pull Request
        if: ${{ failure() }} 
        uses: peter-evans/create-pull-request@v5
        with:
          # Make changes to pull request here
          author: ${{ github.actor }}
          title: Action Changes by create-pull-request action
