name: Merge any release or staging branch to develop
permissions:
  contents: write
  pull-requests: write
on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'merge/**'
env:
  GITHUB_TOKEN: ${{ secrets.AUTOMATION_ACCESS_TOKEN }}
  MERGE_LABELS: "automerge"
  MERGE_REMOVE_LABELS: "merge-failed"
jobs:
  merge-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create Pull Request
        uses: repo-sync/pull-request@master
        with:
          destination_branch: 'main'
          source_branch: '${{ github.ref_name }}'
          pr_title: "[Automation] ${{ github.ref_name }} into develop" # Title of pull request
          pr_body: 'Pr created by automation to run tests'
          pr_assignee: ${{github.actor}}                         # Comma-separated list (no spaces)
          pr_label: "merge-failed,automerge"             # Comma-separated list (no spaces)
          pr_draft: false                                # Creates pull request as draft 
          
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
