name: Create PR from merge/* to dev
permissions:
  contents: write
  pull-requests: write
on:
  pull_request_target:
    types:
      - labeled
      - closed
    branches:
      - 'merge/**'
env:
  GITHUB_TOKEN: ${{ secrets.AUTOMATION_ACCESS_TOKEN }}
jobs:
  create-pr-to-develop:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create Pull Request
        uses: repo-sync/pull-request@master
        with:
          destination_branch: 'main'
          source_branch: '${{ github.ref_name }}'
          pr_title: "[Automation] ${{ github.ref_name }} into develop" # Title of pull request
          pr_body: 'Pr created by automation to run tests'
          pr_assignee: ${{github.actor}}                         # Comma-separated list (no spaces)
          pr_label: "merge-failed,automerge"             # Comma-separated list (no spaces)
          pr_draft: false                                # Creates pull request as draft
